# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:24:13+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union
from uuid import UUID

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, UnsuportedSecurityStub
from fastapi import Header, Path, Query, UploadFile
from pydantic import conint

from models import (
    Association,
    AssociationsObjectIdGetResponse,
    FileObject,
    Files,
    FilesFileIdAssociationsGetResponse,
    Folder,
    FoldersGetResponse,
    Sort,
)

app = MCPProxy(
    contact={
        'email': 'api@xero.com',
        'name': 'Xero Platform Team',
        'url': 'https://developer.xero.com',
        'x-twitter': 'XeroAPI',
    },
    description='These endpoints are specific to Xero Files API',
    termsOfService='https://developer.xero.com/xero-developer-platform-terms-conditions/',
    title='Xero Files API',
    version='2.9.4',
    servers=[
        {'description': 'Xero Files API', 'url': 'https://api.xero.com/files.xro/1.0/'}
    ],
)


@app.get(
    '/Associations/{ObjectId}',
    description=""" By passing in the appropriate options, """,
    tags=['file_association_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_associations_by_object(
    object_id: UUID = Path(..., alias='ObjectId'),
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'),
):
    """
    Retrieves an association object using a unique object ID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Files',
    tags=['file_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_files(
    pagesize: Optional[conint(le=100)] = None,
    page: Optional[conint(ge=1)] = None,
    sort: Optional[Sort] = None,
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'),
):
    """
    Retrieves files
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Files',
    tags=['file_operations', 'folder_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def upload_file(
    folder_id: Optional[UUID] = Query(None, alias='FolderId'),
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'),
    file: UploadFile = ...,
):
    """
    Uploads a File
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/Files/{FileId}',
    description=""" Delete a specific file """,
    tags=['file_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def delete_file(
    file_id: UUID = Path(..., alias='FileId'),
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'),
):
    """
    Deletes a specific file
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Files/{FileId}',
    tags=['file_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_file(
    file_id: UUID = Path(..., alias='FileId'),
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'),
):
    """
    Retrieves a file by a unique file ID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/Files/{FileId}',
    description=""" Updates file properties of a single file """,
    tags=['file_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def update_file(
    file_id: UUID = Path(..., alias='FileId'),
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'),
    body: FileObject = None,
):
    """
    Update a file
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Files/{FileId}/Associations',
    description=""" By passing in the appropriate options, 
 """,
    tags=['file_operations', 'file_association_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_file_associations(
    file_id: UUID = Path(..., alias='FileId'),
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'),
):
    """
    Retrieves a specific file associations
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Files/{FileId}/Associations',
    description=""" By passing in the appropriate options, you can create a new folder """,
    tags=['file_association_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def create_file_association(
    file_id: UUID = Path(..., alias='FileId'),
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'),
    body: Association = None,
):
    """
    Creates a new file association
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/Files/{FileId}/Associations/{ObjectId}',
    description=""" By passing in the appropriate options, you can create a new folder """,
    tags=['file_operations', 'file_association_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def delete_file_association(
    file_id: UUID = Path(..., alias='FileId'),
    object_id: UUID = Path(..., alias='ObjectId'),
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'),
):
    """
    Deletes an existing file association
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Files/{FileId}/Content',
    description=""" By passing in the appropriate options, retrieve data for specific file """,
    tags=['file_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_file_content(
    file_id: UUID = Path(..., alias='FileId'),
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'),
):
    """
    Retrieves the content of a specific file
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Folders',
    description=""" By passing in the appropriate options, you can search for available folders """,
    tags=['folder_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_folders(
    sort: Optional[Sort] = None,
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'),
):
    """
    Retrieves folders
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/Folders',
    description=""" By passing in the appropriate properties, you can create a new folder """,
    tags=['folder_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def create_folder(
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'), body: Folder = None
):
    """
    Creates a new folder
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/Folders/{FolderId}',
    description=""" By passing in the appropriate ID, you can delete a folder """,
    tags=['folder_operations', 'file_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def delete_folder(
    folder_id: UUID = Path(..., alias='FolderId'),
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'),
):
    """
    Deletes a folder
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Folders/{FolderId}',
    description=""" By passing in the appropriate ID, you can search for specific folder """,
    tags=['folder_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_folder(
    folder_id: UUID = Path(..., alias='FolderId'),
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'),
):
    """
    Retrieves specific folder by using a unique folder ID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/Folders/{FolderId}',
    description=""" By passing in the appropriate ID and properties, you can update a folder """,
    tags=['folder_operations', 'file_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def update_folder(
    folder_id: UUID = Path(..., alias='FolderId'),
    xero_tenant_id: str = Header(..., alias='xero-tenant-id'),
    body: Folder = ...,
):
    """
    Updates an existing folder
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Inbox',
    description=""" Search for the user inbox """,
    tags=['folder_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_inbox(xero_tenant_id: str = Header(..., alias='xero-tenant-id')):
    """
    Retrieves inbox folder
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
