# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:24:13+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, Field, RootModel


class Folder(BaseModel):
    Email: Optional[str] = Field(
        None,
        description='The email address used to email files to the inbox. Only the inbox will have this element.',
        examples=['foo@bar.com'],
    )
    FileCount: Optional[int] = Field(
        None, description='The number of files in the folder', examples=[5]
    )
    Id: Optional[UUID] = Field(
        None,
        description='Xero unique identifier for a folder  Files',
        examples=['4ff1e5cc-9835-40d5-bb18-09fdb118db9c'],
    )
    IsInbox: Optional[bool] = Field(
        None,
        description='to indicate if the folder is the Inbox. The Inbox cannot be renamed or deleted.',
        examples=[True],
    )
    Name: Optional[str] = Field(
        None, description='The name of the folder', examples=['assets']
    )


class Folders(BaseModel):
    Folders: Optional[List[Folder]] = None


class ObjectGroup(Enum):
    Account = 'Account'
    BankTransaction = 'BankTransaction'
    Contact = 'Contact'
    CreditNote = 'CreditNote'
    Invoice = 'Invoice'
    Item = 'Item'
    ManualJournal = 'ManualJournal'
    Overpayment = 'Overpayment'
    Payment = 'Payment'
    Prepayment = 'Prepayment'
    Receipt = 'Receipt'


class ObjectType(Enum):
    Unknown = 'Unknown'
    Accpay = 'Accpay'
    AccPayCredit = 'AccPayCredit'
    AccPayPayment = 'AccPayPayment'
    AccRec = 'AccRec'
    AccRecCredit = 'AccRecCredit'
    AccRecPayment = 'AccRecPayment'
    Adjustment = 'Adjustment'
    ApCreditPayment = 'ApCreditPayment'
    ApOverPayment = 'ApOverPayment'
    ApOverPaymentPayment = 'ApOverPaymentPayment'
    ApOverPaymentSourcePayment = 'ApOverPaymentSourcePayment'
    ApPrepayment = 'ApPrepayment'
    ApPrepaymentPayment = 'ApPrepaymentPayment'
    ApPrepaymentSourcePayment = 'ApPrepaymentSourcePayment'
    ArCreditPayment = 'ArCreditPayment'
    ArOverPayment = 'ArOverPayment'
    ArOverpaymentPayment = 'ArOverpaymentPayment'
    ArOverpaymentSourcePayment = 'ArOverpaymentSourcePayment'
    ArPrepayment = 'ArPrepayment'
    ArPrepaymentPayment = 'ArPrepaymentPayment'
    ArPrepaymentSourcePayment = 'ArPrepaymentSourcePayment'
    CashPaid = 'CashPaid'
    CashRec = 'CashRec'
    ExpPayment = 'ExpPayment'
    ManJournal = 'ManJournal'
    PurchaseOrder = 'PurchaseOrder'
    Receipt = 'Receipt'
    Transfer = 'Transfer'
    Account = 'Account'
    Contact = 'Contact'
    Business = 'Business'
    Employee = 'Employee'
    Person = 'Person'
    User = 'User'
    Org = 'Org'
    FixedAsset = 'FixedAsset'
    PayRun = 'PayRun'
    PriceListItem = 'PriceListItem'
    Bank = 'Bank'
    Current = 'Current'
    Equity = 'Equity'
    Expense = 'Expense'
    Fixed = 'Fixed'
    Liability = 'Liability'
    Prepayment = 'Prepayment'
    Revenue = 'Revenue'
    Sales = 'Sales'
    Overheads = 'Overheads'
    Depreciatn = 'Depreciatn'
    OtherIncome = 'OtherIncome'
    DirectCosts = 'DirectCosts'
    Currliab = 'Currliab'
    Termliab = 'Termliab'
    NonCurrent = 'NonCurrent'


class User(BaseModel):
    FirstName: Optional[str] = Field(
        None, description='First name of user', examples=['John']
    )
    FullName: Optional[str] = Field(
        None, description='Last name of user', examples=['Smith']
    )
    Id: UUID = Field(
        ...,
        description='Xero identifier',
        examples=['4ff1e5cc-9835-40d5-bb18-09fdb118db9c'],
    )
    LastName: Optional[str] = Field(
        None, description='Last name of user', examples=['Smith']
    )
    Name: Optional[str] = Field(
        None,
        description='Key is Name, but returns Email address of user who created the file',
        examples=['john.smith@mail.com'],
    )


class Sort(Enum):
    Name = 'Name'
    Size = 'Size'
    CreatedDateUTC = 'CreatedDateUTC'


class FilesPostRequest(BaseModel):
    body: Optional[str] = None
    filename: Optional[str] = None
    mimeType: Optional[str] = None
    name: Optional[str] = Field(
        None, description='exact name of the file you are uploading'
    )


class FoldersGetResponse(RootModel[List[Folder]]):
    root: List[Folder]


class Association(BaseModel):
    FileId: Optional[UUID] = Field(
        None, description='The unique identifier of the file'
    )
    ObjectGroup_1: Optional[ObjectGroup] = Field(None, alias='ObjectGroup')
    ObjectId: Optional[UUID] = Field(
        None,
        description='The identifier of the object that the file is being associated with (e.g. InvoiceID, BankTransactionID, ContactID)',
    )
    ObjectType_1: Optional[ObjectType] = Field(None, alias='ObjectType')


class FileObject(BaseModel):
    CreatedDateUtc: Optional[str] = Field(
        None,
        description='Created date in UTC',
        examples=['2020-12-03T19:04:58.6970000'],
    )
    FolderId: Optional[UUID] = Field(
        None,
        description="Folder relation object's UUID",
        examples=['0f8ccf21-7267-4268-9167-a1e2c40c84c8'],
    )
    Id: Optional[UUID] = Field(
        None,
        description="File object's UUID",
        examples=['d290f1ee-6c54-4b01-90e6-d701748f0851'],
    )
    MimeType: Optional[str] = Field(
        None,
        description='MimeType of the file (image/png, image/jpeg, application/pdf, etc..)',
        examples=['image/jpeg'],
    )
    Name: Optional[str] = Field(None, description='File Name', examples=['File2.jpg'])
    Size: Optional[int] = Field(
        None, description='Numeric value in bytes', examples=[3615]
    )
    UpdatedDateUtc: Optional[str] = Field(
        None,
        description='Updated date in UTC',
        examples=['2020-12-03T19:04:58.6970000'],
    )
    User_1: Optional[User] = Field(None, alias='User')


class Files(BaseModel):
    Items: Optional[List[FileObject]] = None
    Page: Optional[int] = Field(None, examples=[1])
    PerPage: Optional[int] = Field(None, examples=[50])
    TotalCount: Optional[int] = Field(None, examples=[2])


class AssociationsObjectIdGetResponse(RootModel[List[Association]]):
    root: List[Association]


class FilesFileIdAssociationsGetResponse(RootModel[List[Association]]):
    root: List[Association]
